version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: fastapi_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/app:/code/app
    restart: always